name: megapose-m1
channels:
   - conda-forge
   - pytorch
   - anaconda
   - defaults
dependencies:
  - python=3.9
  - pip
  - wget
  - python-wget
  - joblib
  - ipython
  - ipykernel
  - jupyterlab
  - notebook
  - nb_conda_kernels
  - pillow
  - ipywidgets
  - rclone
  - pip:
      - torch
      - torchvision
      - torchaudio
      - meshcat
      - omegaconf
      - simplejson
      - line_profiler
      - opencv-python
      - tqdm
      - lxml
      - transforms3d
      - joblib
      - xarray
      - pandas
      - matplotlib
      - bokeh
      - plyfile
      - trimesh
      - ipdb
      - colorama
      - pyyaml
      - ipykernel
      - scipy
      - pypng
      - h5py
      - seaborn
      - pyarrow
      - open3d
      - structlog
      - imageio
      - progressbar
      - pyyaml
      - psutil
      - webdataset
      - opencv-contrib-python
      - roma
      - kornia